remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false

title: AIに教えてもらうC++
description: [A short description of your site's purpose]
show_downloads: false
google_analytics: G-QNN9HY6KJD
